FishCar = {
	body_data = {
		bounds = { 0, 0, 42, 0, 58, 8, 58, 22, 48, 30, 24, 30, 0, 30 },
		max_vel = 100,
		max_motor_torque = 10000,
		img = "Assets/fish/body.png",
		img_offset = { x = 0, y = 0 },
		scale = { x = 2, y = 2 },
	},
	wheels_data = {
		{
			img = "Assets/fish/w.png",
			radius = 7,
			position_joint_offset = { x = 10, y = 35 },
			ratio_damp = 1,
			spring_frec = 5,
			friction = 1,
			motor_enable = true,
			restitution = 0,
			scale = { x = 2, y = 2 },
		},
		{
			img = "Assets/fish/w.png",
			radius = 7,
			position_joint_offset = { x = 29, y = 35 },
			ratio_damp = 1,
			spring_frec = 5,
			friction = 1,
			motor_enable = true,
			restitution = 0,
			scale = { x = 2, y = 2 },
		},
		{
			img = "Assets/fish/w.png",
			radius = 7,
			position_joint_offset = { x = 48, y = 35 },
			ratio_damp = 1,
			spring_frec = 5,
			friction = 1,
			motor_enable = true,
			restitution = 0,
			scale = { x = 2, y = 2 },
		},
	},
}
